name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t chotuve/media-server .

  test:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Test the Docker image
      run: docker run chotuve/media-server yarn test
    
